global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # This scrapes Prometheus itself

  # Example of scraping another target (e.g., an app or exporter)
  - job_name: 'my_app'
    static_configs:
      - targets: ['localhost:8080']  # Replace with your application's metrics endpoint
